<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">

            <?php if (!empty($user)) : ?>
                <a class="navbar-brand" href="index.php?route=profile">
                    <?= htmlspecialchars($user->getFirstName()) ?> 
                    <?= htmlspecialchars($user->getLastName()) ?>
                </a>
            <?php else : ?>
                <a class="navbar-brand" href="index.php">Camp Life</a>
            <?php endif; ?>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <a class="nav-link" href="index.php">Accueil</a>
                    </li>

                    <?php if (!empty($user)) : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="index.php?route=logout">Déconnexion</a>
                        </li>
                    <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="index.php?route=register">Inscription</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="index.php?route=login">Connexion</a>
                        </li>
                    <?php endif; ?>

                    <?php if (!empty($user) && $user->getRole() === "ADMIN") : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="index.php?route=list">List</a>
                        </li>
                    <?php endif; ?>

                </ul>
            </div>
        </div>
    </nav>
</header>