<section id="login">
    <h1>Connexion</h1>
    <form action="index.php?action=login" method="post">
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>

        <label for="password">Mot de passe:</label>
        <input type="password" id="password" name="password" required>

        <button type="submit">Connexion</button>
    </form>

    <p>Vous n'avez pas de compte? <a href="index.php?action=createAccount">Créez-en un</a></p>
</section>