<section id="register">
    <h1>Inscription</h1>
    <form action="index.php?action=register" method="post">
        <label for="firstName">Prénom:</label>
        <input type="text" id="firstName" name="firstName" required>

        <label for="lastName">Nom:</label>
        <input type="text" id="lastName" name="lastName" required>

        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required>

        <label for="password">Mot de passe:</label>
        <input type="password" id="password" name="password" required>

        <label for="confirmPassword">Confirmez le mot de passe:</label>
        <input type="password" id="confirmPassword" name="confirmPassword" required>

        <button type="submit">Créer un compte</button>
    </form>

    <p>Vous avez déjà un compte? <a href="index.php?action=login">Connectez-vous ici</a></p>
</section>