<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="assets/styles/css/style.css?v=<?php echo filemtime('assets/styles/css/style.css'); ?>">
</head>
<body>
    <?php 
        require "View/partial/_header.phtml";
    ?>

    <section id="mainSec">
        <?php
            require "View/$template.phtml";
        ?>
    </section>

    <?php 
        require "View/partial/_footer.phtml";
    ?>
</body>
</html>